#!/usr/bin/python

import sys

writeToFile = "eepromdata.r"
header = bytearray([0x01, 0x02, 0x03, 0x04])

##########parse args##########
##
if len(sys.argv) < 2:
	print "usage: genEEPROMFile id [outfile]  \n\t(default outfile="+writeToFile+")"
	sys.exit(1)

id = int(sys.argv[1])
if id < 0 or id >= 256:
	print "Error, id does not satisfy (0 <= id < 256)"
	sys.exit(1)

print "id = "+str(id)

if len(sys.argv) > 2:
	writeToFile = sys.argv[2]

print "outfile = \""+writeToFile+"\""
##
##########################


f = open(writeToFile, "wb")
ba = bytearray(512)
for i in range(512):
	ba[i] = 0xff
for i in range(1,5):
	writeTo = i*10
	for j in range(len(header)):
		ba[writeTo+j]=header[j]
	writeTo += len(header)
	ba[writeTo] = id
	ba[writeTo+1] = (id+10) % 256
f.write(ba)
f.close()
